services:
  grcp-auth-service:
    container_name: grcp-auth-service
    image: grcp-auth-image
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - grcp-auth-db
  grcp-auth-db:
    container_name: grcp-auth-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}