services:
  grpc-auth-service:
    container_name: grpc-auth-service
    image: grpc-auth-image
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - grpc-auth-db
  grpc-auth-db:
    container_name: grpc-auth-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}